name: Test build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout source code
        uses: actions/checkout@main

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
          cache: 'npm'
    
      - name: Install dependencies
        run: npm install
      
      - name: Build bundle
        run: npm run build-all

  lint:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout source code
        uses: actions/checkout@main

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
          cache: 'npm'
    
      - name: Install dependencies
        run: npm install
      - name: Check style JS
        run: npm run lint
