name: Test build

on:
  pull_request:
    branches:
      - master
    types:
      - reopened
      - labeled
      - unlabeled

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout source code
        uses: actions/checkout@main

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
          cache: 'npm'
    
      - name: Install dependencies
        run: npm install
      
      - name: Build bundle
        run: npm run build-all

  lint:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout source code
        uses: actions/checkout@main

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
          cache: 'npm'
    
      - name: Install dependencies
        run: npm install
      - name: Check style JS
        run: npm run lint
    
  add_comment:
    name: 'Add Comment'
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: Please set a versioning label of either `major`, `minor`, or `patch` to the pull request.
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  check_labels:
    needs: add_comment
    name: 'Check PR Labels'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mheap/github-action-required-labels@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 1
          labels: 'major, minor, patch'
